--- # В данном файле описана только часть требований, при реальном тестировании сайта, требований будет в разы больше
functional:
  - Пользователь должен иметь возможность создать игру
  - Пользователь должен иметь возможность поучаствовать в игре
  - Пользователи должны иметь возможность играть на скорость
  - Пользователь должен иметь возможность видеть код другого игрока
  - Пользователь должен видеть вывод тестов другого игрока
  - Пользователь должен иметь возможность менять язык программирования во время игры
  - Пользователь должен иметь возможность играть с ботом
  - Пользователь должен иметь возможность выбирать игру
  - Пользователь должен иметь возможность выбирать сложность игры
  - Пользователь должен иметь возможность следить за ходом игры других пользователей
  - Пользователи должны иметь возможность общаться в чате 
  - Завершенная игра должна быть доступна в записи
  - Запись игры должна воспроизводиться через проигрыватель
  - Пользователь должен иметь рейтинг
  - Пользователь должен иметь возможность сменить в профиле основной язык программирования
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность сменить язык с английского на русский в любой момент
  - Дата в History должна отображаться с указанием года
  - Основная страница сайта должна умещаться на один экран, без необходимости скролить
  - Пользователь должен иметь возможность подписаться на Премиум по ссылке в окне Restricted Content
